# Generated by Django 3.1.2 on 2020-11-05 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simu',
            name='author',
        ),
        migrations.AddField(
            model_name='simu',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
