# Generated by Django 3.1.2 on 2020-11-05 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simu', '0002_auto_20201105_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simu',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
