# Generated by Django 3.1.2 on 2020-11-05 05:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simu', '0003_auto_20201105_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='simu',
            name='liked_users',
            field=models.ManyToManyField(related_name='liked_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
