# Generated by Django 3.1.2 on 2020-11-05 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simu', '0008_auto_20201105_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='simu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simu.simu'),
        ),
    ]
